# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AguajeDetection
                                 A QGIS plugin
 This plugin adds an algorithm to detect Aguaje in a raster layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-12-12
        copyright            : (C) 2019 by Susan Palacios, University of Brescia
        email                : s.palaciossalcedo@studenti.unibs.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Susan Palacios, University of Brescia'
__date__ = '2019-12-12'
__copyright__ = '(C) 2019 by Susan Palacios, University of Brescia'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AguajeDetection class from file AguajeDetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aguaje_detection_processing import AguajeDetectionPlugin
    return AguajeDetectionPlugin(iface)#return AguajeDetectionPlugin()
