# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AguajeDetection
                                 A QGIS plugin
 This plugin adds an algorithm to detect Aguaje in a raster layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-12-12
        copyright            : (C) 2019 by Susan Palacios, University of Brescia
        email                : s.palaciossalcedo@studenti.unibs.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Susan Palacios, University of Brescia'
__date__ = '2019-12-12'
__copyright__ = '(C) 2019 by Susan Palacios, University of Brescia'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,                       
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterVectorDestination,
                       QgsFeatureSink,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)

#from .processing.aguaje_detection import classifyImage
import os
import inspect
from qgis.PyQt.QtGui import QIcon #icon
from .aguaje_algo import aguaje_detection
cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
class AguajeDetectionAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    #OUTPUT = 'OUTPUT'
    #INPUT = 'INPUT'

    INPUT_RASTER = 'INPUT_RASTER'
    #INPUT_MODEL = 'INPUT_MODEL'
    OUTPUT_RASTER = 'OUTPUT_RASTER'
    #OUTPUT_LAYER = 'OUTPUT_LAYER'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        #inputs
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT_RASTER,
                self.tr('Input raster')
            )
        )


        # output
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT_RASTER,
                self.tr('Output raster'),
                optional=False
            )
        )

        """self.addParameter(
            QgsProcessingParameterVectorDestination(
                self.OUTPUT_LAYER,
                self.tr('Output layer'),
                optional=False
            )
        )"""

        # We add the input vector features source. It can have any kind of
        # geometry.
        """self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )"""

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        """self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )"""

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.

        INPUT_RASTER = self.parameterAsRasterLayer(
            parameters, self.INPUT_RASTER, context)

        
        OUTPUT_RASTER = self.parameterAsOutputLayer(
            parameters, self.OUTPUT_RASTER, context)

        if feedback.isCanceled():
            return {}

        """OUTPUT_LAYER = self.parameterAsOutputLayer(
            parameters, self.OUTPUT_LAYER, context)"""

        """source = self.parameterAsSource(parameters, self.INPUT, context)
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())"""

        # Compute the number of steps to display within the progress bar and
        # get features from source
        """total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()"""

        #for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
        #if feedback.isCanceled():
            #break

            # Add a feature in the sink
            #sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            #feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        """return {self.OUTPUT_RASTER: OUTPUT_RASTER,
                self.OUTPUT_LAYER: OUTPUT_LAYER}
        #return {self.OUTPUT: dest_id}"""
        OUTPUT_RASTER = aguaje_detection.apply_aguaje(INPUT_RASTER.source(),OUTPUT_RASTER)
        if feedback.isCanceled():
            return {}
        #test=INPUT_RASTER.source()
        #test2=OUTPUT_RASTER.s()
        print(OUTPUT_RASTER)
        return {self.OUTPUT_RASTER: OUTPUT_RASTER}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Detection algorithm'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def icon(self):#icon
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]#icon
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'logo.png')))#icon
        return icon#icon

    def createInstance(self):
        return AguajeDetectionAlgorithm()
